### ISSUE TITLE
Some Kicad library are missing

### ISSUE THREAD

**Issue by BenRoe** [rsheldiii/Keebcard#1]
I will add a on/off switch to the pcb.
Problem is that some symbol libraries are missing (bobness_card.lib and KeebCard.lib).
Also the footprints are in six different libraries. Can you move the parts in one symbol and one footprint library?
Or please zip all libraries and upload it. I can merge if you wan't.
![Bildschirmfoto 2019-11-01 um 23 36 40](https://user-images.githubusercontent.com/643834/68060556-29d30280-fd01-11e9-80cd-98f7606b8bdf.png)

**Comment by rsheldiii** [comment]
Whoops, totally missed this, sorry about that. 

None of those libraries are used, so they are safe to ignore. I've removed them from the library tables so this should be all set.

thanks for pointing this out!
